<?php

/*
* Implements hook_menu.
*/

function menu_magic_menu(){
	$items = array();

	$items['magic'] = array(
		'title' => 'A Little Magic',
		'page callback' => 'menu_magic_basic',
		//'access callback' => 'user_access', // user_content('access content')
		'access arguments' => array('access content'),
	);

	$items['magic/%'] = array(
		'title' => 'A Little More Magic',
		'page callback' => 'menu_magic_extra',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'file' => 'menu_magic.extra.inc',
	);

	$items['users/%/magic'] = array(
		'title' => 'Magic',
		'description' => 'Magic for Users',
		'page callback' => 'menu_magic_user_tab',
		'page arguments' => array(1),
		'access callback' => 'user_access',
		'access arguments' => array('administer users'),
		'file' => 'menu_magic.user.inc',
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	//%node autoloader
	$items['node/%node/magic'] = array(
		'title' => 'Magic',
		'description' => 'Do Amazing and Wonderful things',
		'page callback' => 'menu_magic_node_context',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'file' => 'menu_magic.context.inc',
		'type' => MENU_LOCAL_TASK,
		'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
	);
	
	return $items;
}

function menu_magic_basic(){
	$content = array();

	$content['raw_markup'] = array(
		'#type' => 'markup',
		'#markup' => '<p>Woah! That\'s so Magical!</p>'
	);

	return $content;
}